package man.dan.converter.lexer;

public enum Tag {
    AND, OR, EQUAL, GREATER, LESS, MINUS, PLUS, MUL, NUM, TRUE, FALSE, CONVEYOR,
    ELEMENT, MAP, FILTER, CL_BRACE, OP_BRACKET, CL_BRACKET, BOOLEAN, EOS;
}
